<?php

namespace WebinoNameDayLib;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-08-26 at 11:39:58.
 */
class FactoryTest
     extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Factory
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Factory;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers WebinoNameDayLib\Factory::create
     */
    public function testCreate()
    {
        $locale  = 'sk_SK';
        $nameDay = $this->object->create($locale);

        $this->assertInstanceOf('WebinoNameDayLib\NameDay', $nameDay);
    }

    /**
     * @covers WebinoNameDayLib\Factory::create
     */
    public function testCreateInvalidLocale()
    {
        $this->setExpectedException('InvalidArgumentException');

        $locale  = 'unknown';
        $this->object->create($locale);
    }

    /**
     * @covers WebinoNameDayLib\Factory::create
     */
    public function testCreateUnknown()
    {
        $this->setExpectedException('RuntimeException');

        $locale  = 'en_US';
        $this->object->create($locale);
    }
}
